In [4]:
import global_new  as gl
import numpy as np
import sklearn.feature_selection as sfs

datamat=gl.dataMat
labelmat=gl.labelMat

mean_label=np.mean(labelmat)#average of label
mean_feature=np.mean(datamat,axis=0)#average of each feature
[n_sample,n_feature]=np.shape(datamat)

In [10]:
(labelmat-mean_label)

array([-0.46249033, -0.46249033, -0.46249033, ...,  0.53750967,
        0.53750967,  0.53750967])

In [17]:
j=0
test=(datamat[:,j]-mean_feature[j])*(labelmat-mean_label)
np.shape(test)
sum(test)

-17.160092807424629

In [20]:
j=0
datamat[:,j]-mean_feature[j]
#np.square(datamat[:,j]-mean_feature[j])

array([-1.19257541,  0.80742459,  0.80742459, ..., -1.19257541,
        0.80742459, -1.19257541])

In [21]:
np.square(datamat[:,j]-mean_feature[j])

array([ 1.4222361 ,  0.65193447,  0.65193447, ...,  1.4222361 ,
        0.65193447,  1.4222361 ])

In [27]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A': 'foo bar foo bar foo bar foo foo'.split(),
                   'B': 'one one two three two two one three'.split(),
                   'C': np.arange(8)+0.1, 'D': np.arange(8) * 2})
print(df)

     A      B    C   D
0  foo    one  0.1   0
1  bar    one  1.1   2
2  foo    two  2.1   4
3  bar  three  3.1   6
4  foo    two  4.1   8
5  bar    two  5.1  10
6  foo    one  6.1  12
7  foo  three  7.1  14


In [28]:
test=df[df.C>3]
test

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3</th>
      <td>bar</td>
      <td>three</td>
      <td>3.1</td>
      <td>6</td>
    </tr>
    <tr>
      <th>4</th>
      <td>foo</td>
      <td>two</td>
      <td>4.1</td>
      <td>8</td>
    </tr>
    <tr>
      <th>5</th>
      <td>bar</td>
      <td>two</td>
      <td>5.1</td>
      <td>10</td>
    </tr>
    <tr>
      <th>6</th>
      <td>foo</td>
      <td>one</td>
      <td>6.1</td>
      <td>12</td>
    </tr>
    <tr>
      <th>7</th>
      <td>foo</td>
      <td>three</td>
      <td>7.1</td>
      <td>14</td>
    </tr>
  </tbody>
</table>
</div>

In [51]:
df=gl.dataMat
d=df[:,2]
test=np.std(d,ddof=1)
test



0.30080635370864317